### PR TITLE
Added Doxygen documentation for all files

### LINKED ISSUE #4: Automate documentation generation
Use Doxygen or other documentation generators for generating detailed and up-to-date documentation.

### PR DESCRIPTION
**Pull request by FloatingFowl**
All class (public) members have been documented (including the operators) along with the other helper/utility functions present in `include/functions`. Opening `docs/html/index.html` in a browser will give the documentation.

To regenerate the documentation, run `cd docs; doxygen Doxyfile` from the root directory after installing Doxygen.

Currently the documentation must be updated manually. The next step can be to integrate it with Travis.CI and possibly link to the documentation from the repo website.

Closes #4.

### CODE REVIEW

**Comment by FloatingFowl** [comment]
@faheel  The doc files have been removed

**Comment by faheel** [comment]
I'm quite busy currently so I'll only be able to review the updated documentation in detail by the end of next week (May 11).

**Comment by faheel** [comment]
@FloatingFowl I recently made a new branch named `docs` for improving the documentation, as then any changes made to documentation will not conflict with changes made to code on the `master` branch. So I request you to close this PR and open a new one against the `docs` branch. Sorry for any inconvenience.

**Comment by faheel** [comment]
@FloatingFowl Thanks a lot for your work on this! I've been working on other projects and had forgotten about this PR, so I apologize for merging it after such a long time. Thank you for your patience :slightly_smiling_face:

**Comment by faheel** [comment]
I've merged this in the `docs` branch for now, which will be merged into `master` after a few more changes (that are being done in PR #50).

**Pull request merged**
